### ISSUE TITLE
PRACTICA_LÓPEZ_DOMÍNGUEZ

### ISSUE THREAD

**Issue by 23620031** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-23620031#1]
[Uploading López_D
[López_Domínguez_Isaías_Practica_1.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-23620031/files/12591168/Lopez_Dominguez_Isaias_Practica_1.pdf)
omínguez_Isaías_Practica_1.pdf…]()

**Comment by Felix-Angel** [comment]
PORTADA 25%
PROCEDIMIENTO 25%
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS (falto enumerar la lista de figuras) 15%
RESULTADOS Y CONCLUSIONES 25%
CALIFICACION: 90/100
CALIFICACION: 18/20
CALIFICADO POR: "EQUIPO DE MAYRA, DIEGO, DANIEL, FELIX"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
